### ISSUE TITLE
Incorrect Animated Color Lerp

### ISSUE THREAD

**Issue by seabassjh** [linebender/velato#8]
in `runtime::mode::value`, `Lerp` impl for `Color` has a typo which leads to incorrect behavior
<img width="507" alt="image" src="https://github.com/linebender/velato/assets/20546772/74035ff2-2356-4c10-a1e0-46f6fc1df8ef">

**Comment by waywardmonkeys** [comment]
Submitted PR #9 for that. Thanks!
